name: Maven CI/CD

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Installing Git keaks 
      run : |
        wget -q -o gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/download/v8.18.0/gitleaks_8.18.0_linux_x64.tar.gz
        ls -l
        tar -xzvf gitleaks.tar.gz
        chmod +x gitleaks
        sudo mv gitleaks /usr/local/bin/
        
    - name: Run git leaks
      run : |
         gitleaks detect --redact
     
        
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: clean project with Maven
      run: mvn clean --file pom.xml
    - name: compile  project with Maven
      run: mvn compile --file pom.xml
    - name: deploy  project with Maven
      run: mvn clean install spring-boot:repackage --file pom.xml
      
